version: 2

sources:
  - name: mileage_source
    database: mileage-495412
    schema: MileageData
    tables:
      - name: Mileage
        columns:
          - name: Column1
            description: primary key
            data_tests:
              - not_null
              - unique